#!/usr/bin/env bash
# shellcheck shell=bash
#
# scripts/mod-upgrade

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/lib.sh"

need_cmd go-mod-upgrade

info "Running go-mod-upgrade..."

go-mod-upgrade

ok "... report complete."
printf '\n'
