#!/usr/bin/env bash
# shellcheck shell=bash
#
# scripts/tidy

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/lib.sh"

need_cmd go
need_cmd gofmt

tidy() {
  info "Running tidy..."

  go mod tidy -v

  ok "... complete."
  printf '\n'
}

fmt() {
  info "Running gofmt..."

  gofmt -w .

  ok "... complete."
  printf '\n'
}

main() {
  info "Cleaning up project..."
  printf '\n'
  tidy
  fmt
  ok "... cleaning complete."
}

main "$@"
