name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run tests
        run: go test ./... -race -cover

      - name: Run vetting
        run: go vet ./...

      - name: Run security checks
        run: gosec ./...

  style:
    name: formatting-and-linting
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Check formatting
        run: test -z $(go fmt -l -s .)

      - name: Check linting
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false

